name: Run code quality checks

runs:
  using: composite

  steps:
    - name: Check formatting
      shell: bash
      run: yarn formatting:check

    - name: Lint code
      shell: bash
      run: yarn lint

    - name: Check types
      shell: bash
      run: yarn check-types

    - name: Run tests
      shell: bash
      run: yarn test
