name: Check pull request

on:
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup up Node.js environment
        uses: SBence/setup-node-workflow-yarn@master
        with:
          node-version: "*"

      - name: Run code quality checks
        uses: ./.github/actions/check-code-quality

      - name: Create tarball
        run: yarn pack --filename package.tgz

      - name: Test tarball installation
        run: yarn add package.tgz
